#!/usr/bin/env python3
"""Generate daemon/voices.sha256 from the voice catalog in jarvis-config.

The installer already verifies the default voice against a sha256 committed
to this repo. The voice picker in the settings panel did not: it downloaded
any of the other catalog voices over HTTPS and handed the file straight to
onnxruntime. This closes that gap by locking every voice the panel can offer.

Two kinds of file, two ways to get the digest:

  *.onnx       Git-LFS backed. HuggingFace returns the file's sha256 in the
               `x-linked-etag` header, so a HEAD request is enough and there
               is no need to pull 630MB to write the lock. Corroborated: the
               header for en_US-amy-medium matches the digest already in
               daemon/voice-model.sha256, which was produced independently by
               hashing the downloaded file.
  *.onnx.json  A few KB and not LFS-backed, so its etag is a git blob SHA-1,
               not a sha256. Those are downloaded and hashed directly.

Trust model, stated plainly: this records what HuggingFace served at the
moment a human ran it, exactly like tools/genlock.py records what PyPI
published. It does not attest that those bytes were ever good -- it makes any
*later* change to them fail loudly instead of being installed silently.
Regenerate and diff rather than taking the file on faith.

    python3 tools/genvoicelock.py
"""

import hashlib
import os
import re
import sys
import urllib.error
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DAEMON = os.path.join(ROOT, "daemon")
CONFIG_TOOL = os.path.join(DAEMON, "jarvis-config")
OUT = os.path.join(DAEMON, "voices.sha256")

SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


def catalog():
    """VOICE_BASE and VOICE_CATALOG, read out of jarvis-config.

    Parsed rather than imported: jarvis-config imports the daemon, which
    needs the venv, and this is a repo tool that should run on a bare
    interpreter.
    """
    source = open(CONFIG_TOOL, encoding="utf-8").read()
    base = re.search(r'^VOICE_BASE = "([^"]+)"', source, re.M)
    block = re.search(r"^VOICE_CATALOG = \[(.*?)\]", source, re.M | re.S)
    if not base or not block:
        raise SystemExit("could not find VOICE_BASE/VOICE_CATALOG in jarvis-config")
    return base.group(1), re.findall(r'"([^"]+)"', block.group(1))


def voice_url(base, vid, suffix):
    lang, name, quality = vid.split("-")
    family = lang.split("_")[0]
    return f"{base}/{family}/{lang}/{name}/{quality}/{vid}{suffix}"


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    """Stop at the first response instead of following it to the CDN."""

    def redirect_request(self, *_args, **_kwargs):
        return None


def linked_sha256(url):
    """The sha256 HuggingFace publishes for an LFS file, or None.

    `x-linked-etag` is set by the huggingface.co resolve endpoint, which then
    redirects to a CDN whose own ETag is unrelated. Following the redirect
    loses the header -- so this deliberately does not follow it.
    """
    request = urllib.request.Request(url, method="HEAD")
    opener = urllib.request.build_opener(_NoRedirect)
    try:
        with opener.open(request, timeout=60) as response:
            headers = response.headers
    except urllib.error.HTTPError as exc:
        if exc.code not in (301, 302, 303, 307, 308):
            raise
        headers = exc.headers
    etag = (headers.get("x-linked-etag") or "").strip('"')
    return etag if SHA256_RE.match(etag) else None


def downloaded_sha256(url):
    digest = hashlib.sha256()
    with urllib.request.urlopen(url, timeout=120) as response:
        while True:
            chunk = response.read(1 << 16)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def main():
    base, voices = catalog()
    lines = [
        "# Every voice the settings panel can install, and its metadata.",
        "# sha256sum format. Generated by tools/genvoicelock.py -- regenerate",
        "# and diff rather than trusting these by hand.",
    ]
    for vid in voices:
        for suffix in (".onnx", ".onnx.json"):
            url = voice_url(base, vid, suffix)
            digest = linked_sha256(url) if suffix == ".onnx" else None
            how = "lfs"
            if digest is None:
                digest = downloaded_sha256(url)
                how = "hashed"
            print(f"  {vid}{suffix:11} {how:7} {digest}", file=sys.stderr)
            lines.append(f"{digest}  {vid}{suffix}")

    open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"\nwrote {OUT} ({len(lines) - 3} entries)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
